name: 'spend_spent_spent'
version: '2.12.3+123'
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'
description: Client for SpendSpentSpent self hosted expense tracker.
dependencies:
  after_layout: 1.2.0
  animations: 2.1.0
  auto_route: 10.2.0
  cached_network_image: 3.4.1
  dynamic_color: 1.8.1
  easy_debounce: 2.0.3
  fl_chart: 1.1.1
  flutter:
    sdk: flutter
  flutter_animate: 4.5.2
  flutter_bloc: 9.1.1
  flutter_fadein: 2.0.0
  flutter_map: 8.2.1
  flutter_map_heatmap:
    git:
      # https://github.com/tprebs/fluttermap_heatmap/pull/23
      url: https://github.com/ThomasAunvik/fluttermap_heatmap.git
  flutter_notification_listener:
      path: ../../../../flutter_notification_listener
  flutter_settings_ui: 3.0.1
  flutter_svg: 2.2.1
  flutter_timezone: 5.0.0
  freezed_annotation: 3.1.0
  gap: 3.0.1
  get_it: 8.2.0
  http: 1.5.0
  image_picker: 1.2.0
  intl: 0.20.2
  json_annotation: 4.9.0
  jwt_decoder: 2.0.1
  latlong2: 0.9.1
  location: 8.0.1
  logging: 1.3.0
  material_loading_indicator: 1.0.0
  motor: 1.0.1
  oidc: 0.13.0
  oidc_default_store: 0.5.0
  package_info_plus: 9.0.0
  random_string: 2.3.1
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
  share_plus: 12.0.1
  shared_preferences: 2.5.3
  stupid_simple_sheet: 0.6.0+1
  tinycolor2: 3.0.1
  web_socket_channel: 3.0.3
dependency_overrides:
  # Waiting for https://github.com/Lyokone/flutterlocation/issues/1031
  location_platform_interface: ^6.0.1
  location_web:
    git:
      url: https://github.com/Lyokone/flutterlocation
      path: packages/location_web
      ref: location-v8.0.1
dev_dependencies:
  analyzer: any
  auto_route_generator: 10.2.5
  build_runner: 2.10.0
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.3
  json_serializable: 6.11.1
  pubspec_dependency_sorter: 1.0.5
flutter_icons:
  android: false
  ios: true
  image_path_ios: images/ios.png
  image_path_android: images/android.png
flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: fonts/sss.ttf
